# this file uses prebuilt image in dockerhub
services:
  jekyll:
    build: 
      context: .
      args:
        GROUPID: ${DOCKER_GID:-1000}
        GROUPNAME: ${DOCKER_GROUP:-docker}
        USERID: ${DOCKER_UID:-1000}
        USERNAME: ${DOCKER_USER:-jekyll}
    ports:
      - 8080:8080
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
