baseURL                = "https://gallantlab.org/"
title                  = "Gallant Lab"
languageCode           = "en-us"
defaultContentLanguage = "en"
timeZone               = "America/Los_Angeles"

enableRobotsTXT = true
disableKinds    = ["taxonomy", "term", "RSS"]

[params]
  description = "Cognitive, systems and computational neuroscience at UC Berkeley."
  dateFormat  = "January 2, 2006"

[[menu.main]]
  name   = "News"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "People"
  url    = "/people/"
  weight = 2

[[menu.main]]
  name   = "Publications"
  url    = "/publications/"
  weight = 3

[[menu.main]]
  name   = "Brain Viewers"
  url    = "/brain-viewers/"
  weight = 4

[[menu.main]]
  name   = "Data"
  url    = "/data/"
  weight = 5

[[menu.main]]
  name   = "Code"
  url    = "/code/"
  weight = 6

[[menu.main]]
  name   = "Learn"
  url    = "/learn/"
  weight = 7

[[menu.main]]
  name   = "Blog"
  url    = "/blog/"
  weight = 8

[[menu.main]]
  name   = "Join us"
  url    = "/joinus/"
  weight = 9

[markup.goldmark.renderer]
  unsafe = true
